# Docker Compose
# https://docs.docker.com/compose/
#
# Usage: test up

version: '3.9'
services:
  app:
    image: ansible-role-pureftpd-app-test
    environment: &environment
      - STAGE=testing
    build:
      args:
        stage: test
